
language: php

php:
#  - 5.3
#  - 5.4
#  - 5.5
  - 5.6
#  - 7.0
#  - hhvm

services:
  - mongodb

before_script:
  - phpenv config-add travis-php.ini
  - composer self-update
  - composer require doctrine/mongodb:1.2.0 --no-update
  - composer install

script: vendor/bin/phpunit
